### PR TITLE
Updated dependencies to fix set-output warning

### PR DESCRIPTION
**Pull request by yurist38**
Hello,

I've noticed this warning in my CI output, and I'm pretty confident it's coming from this action.
This PR is an attempt to fix it, but I didn't test it myself yet.
I've simply upgraded all dependencies and fixed a couple of small things in the GitHub CLI in order to make it work again.

Screenshot 2023-04-22 at 16 18 40

### CODE REVIEW

**Comment by f0urfingeredfish** [comment]
@jhuleatt could we get some traction on this please? This action seems really popular and it **will stop working on June 1st, 2023 unless fixed**.

**Comment by NKalganov** [comment]
@jhuleatt could you please merge this branch? We have only two weeks left before the main branch becomes outdated without this update. Thank you in advance! 🙏

**Comment by jhuleatt** [comment]
Thank you @yurist38! Really appreciate this!

**Comment by yurist38** [comment]
Awesome! Thank you for reviewing and merging this!

**Pull request merged**
