### PR TITLE
upgrades the runtime to node20, now that 16 is EoL

### PR DESCRIPTION
**Pull request by bkendall**

### CODE REVIEW

**Review by jhuleatt — APPROVED** [review]
Thanks @bkendall!

**Comment by testak-m** [comment]
@bkendall @jhuleatt 
Can this pull request be merged and released?
You can solve the following issues.
#341

**Comment by sam-golioth** [comment]
@bkendall @jhuleatt Is there anything else we need to merge this PR?

**Comment by huggsboson** [comment]
@bkendall any chance you'll merge this soon?

**Comment by testak-m** [comment]
@bkendall @jhuleatt
ping

**Comment by thomasvht** [comment]
Will someone have a look, because due to the EoL we have builds failing.

**Comment by testak-m** [comment]
@inlined
Is it possible to merge this pull request?
This action is used in firebase-tools.

**Review by henrylangenhoven — APPROVED** [review]

**Comment by thomasvht** [comment]
@henrylangenhoven I see the changes are approved which is great. Is there someone who can merge the change? 😄

**Review by developit — APPROVED** [review]

**Comment by developit** [comment]
I don't have merge rights on this repo, sorry.

**Comment by testak-m** [comment]
@developit 
I understand your position.
Thank you for checking.

**Review by testak-m — APPROVED** [review]

**Comment by testak-m** [comment]
@jhuleatt 
Are you still busy?
Don't have time to merge and release this pull request?

**Comment by EricCheungAO** [comment]
> @jhuleatt Are you still busy? Don't have time to merge and release this pull request?

cc @jhuleatt

**Comment by testak-m** [comment]
He seems to be active.
https://github.com/FirebaseExtended/firebase-framework-tools/pull/161

I was relieved to know that he was alive.

**Comment by lesv** [comment]
Does anyone know what version this is.  The CLI is still generating `FirebaseExtended/action-hosting-deploy@v0`, is the updated one v1? (and has it been released to Github)

**Comment by testak-m** [comment]
@lesv 
It seems that it has been merged but not released.
https://github.com/FirebaseExtended/action-hosting-deploy/releases

It has not been released and cannot be used in any version.
v0 refers to v0.7.1.

**Comment by testak-m** [comment]
@jamesdaniels @leoortizz @Yuangwang @sjjj986
He seems busy.
Can I support him and release this pull request?

**Comment by testak-m** [comment]
@jamesdaniels @leoortizz @Yuangwang @sjjj986 @bkendall 
He seems busy.
Can you guys help him make the release?

**Comment by 178inaba** [comment]
I submitted a pull request to firebase-tools to specify the version by hash value.
The warning should disappear once released.
https://github.com/firebase/firebase-tools/pull/7025

**Pull request merged**
