### PR TITLE
Fix deprecated set-output set to sunset June 1st, 2023

### PR DESCRIPTION
**Pull request by f0urfingeredfish**
fixes https://github.com/FirebaseExtended/action-hosting-deploy/issues/247

This updates the "@actions/core" package to fix the [deprecated setOutput](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) warning per Github's instructions.

This warning appears as an annotation when run:
image

Important info on deprecation dates from Github:

> We are monitoring telemetry for the usage of these commands and plan to fully disable them on 31st May 2023. **Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error.**

**NOTE: June 1st, 2023 is when this action will start failing with an error unless fixed.**

### CODE REVIEW

**Comment by f0urfingeredfish** [comment]
I'm getting the CLA sorted. Unless you want me to close this and just upgrade on your end?

**Comment by NKalganov** [comment]
@f0urfingeredfish any luck on the CLA Nick? 😟

**Comment by f0urfingeredfish** [comment]
@NKalganov I have had no luck. I have signed the CLA and so had my company and when I go to have it check again Google gives me a 400 error on this PR CLA check 
image

**Comment by f0urfingeredfish** [comment]
Re-opening to see if CLA check gets triggered again

**Comment by f0urfingeredfish** [comment]
Closing in favor of this PR https://github.com/FirebaseExtended/action-hosting-deploy/pull/279 which includes the same fix and the author has a working CLA check. 

 I also discovered that you can't just upgrade the `@actions/core` package you also need to upgrade `microbundle` because there is a bug in microbundle (parcel) that doesn't bundle the crypto package correctly and you will get this error `Error: crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported` when running the workflow.

**Pull request closed without merging**
