### PR TITLE
Document outputs

### LINKED ISSUE #11: Add deployed URL as an output
Feature request - add GH Actions output that contains the deployed Firebase URL

### PR DESCRIPTION
**Pull request by jhuleatt**
Fixes #11

### CODE REVIEW

**Comment by jhuleatt** [comment]
@mr-smithers-excellent do have time to give some feedback on this PR? I'm honestly not too familiar with outputs, and would appreciate your opinion on what would be useful.

**Comment by jthegedus** [comment]
This looks good to me as a starting point, URLs being the most important feature to integrate automated Cypress and Lighthouse testing.

I would expect the `projectId` targeted by the Action (considering it can find this value by `.firebaserc`) and perhaps the Hosting Deployment Target would also be useful outputs in the future once those features are expanded.

I'd suggest consuming these outputs in the test deployment and just `echo` them to the console in a subsequent step.

**Comment by mr-smithers-excellent** [comment]
@jhuleatt - you nailed it. This was already working functionally, but docs now reflect the `outputs` that are being set in the code. Thanks for incorporating!

**Comment by jhuleatt** [comment]
@mr-smithers-excellent great! Thanks again for the request.

@jthegedus Echoing is a great idea. I've added that to this PR. Deploy target does sound like a helpful output. I've filed #33 to capture that work so we can keep this PR focused on documenting the current outputs.

Thanks both!

**Pull request merged**
